{
 "title": "[66]IPMI-SENSOR-MONITOR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "test",
    "label": "test",
    "query": "\"P2 DTS Therm Mgn\""
   }
  ]
 },
 "panels": [
  { "title": "Process 1 & Process 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Process Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU Process 1 Temperature",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"P1 Temperature\"",
     "timeField": "unixtime"
    },
    {
     "alias": "CPU Process 2 Temperature",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"P2 Temperature\"",
     "timeField": "unixtime"
    }
   ]
  },
  {
   "title": "Process Thermal Margin",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Process 1 Thermal Margin",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "inlineScript": "((-1 * _value) / 80) * 100",
       "meta": {},
       "settings": { "script": { "inline": "((-1 * _value) / 80) * 100" } },
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"P1 DTS Therm Mgn\"",
     "timeField": "unixtime"
    },
    {
     "alias": "Process 2 Thermal Margin",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "inlineScript": "((-1 * _value) / 80) * 100",
       "meta": {},
       "settings": { "script": { "inline": "((-1 * _value) / 80) * 100" } },
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"P2 DTS Therm Mgn\"",
     "timeField": "unixtime"
    }
   ]
  },
  {
   "title": "Panel Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Front Panel Temp",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"Front Panel Temp\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Rear Panel Temp",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"Exit Air Temp\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Baseboard Sensor Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BaseBoard Voltage Regulator Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "P1 VoltageRegulator Temperature",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB P1 VR Temp\"",
     "timeField": "unixtime"
    },
    {
     "alias": "P2 VoltageRegulator Temperature",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB P2 VR Temp\"",
     "timeField": "unixtime"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BB BMC Temp",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"BB BMC Temp\"",
     "timeField": "unixtime"
    },
    {
     "alias": "BB Lft Rear Temp",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"BB Lft Rear Temp\"",
     "timeField": "unixtime"
    },
    {
     "alias": "BB P1 VR Temp",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"BB P1 VR Temp\"",
     "timeField": "unixtime"
    },
    {
     "alias": "BB P2 VR Temp",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"BB P2 VR Temp\"",
     "timeField": "unixtime"
    },
    {
     "alias": "BB Rt Rear Temp",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR: \"BB Rt Rear Temp\"",
     "timeField": "unixtime"
    }
   ]
  },
  { "title": "Power Supply", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Power Supply Input Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Input Power",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"PS1 Input Power\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Supply Input Power(W)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Power Input Power",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"PS1 Input Power\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Baseboard Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "BaseBoard Power +12V",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB +12.0V\"",
     "timeField": "unixtime"
    }
   ]
  },
  {
   "title": "BaseBoard Power +3.3V",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB +3.3V Vbat\"",
     "timeField": "unixtime"
    }
   ]
  },
  {
   "title": "Baseboard Voltage(V)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BB +12.0V",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB +12.0V\"",
     "timeField": "unixtime"
    },
    {
     "alias": "BB +3.3V",
     "bucketAggs": [
      { "field": "unixtime", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"BB +3.3V Vbat\"",
     "timeField": "unixtime"
    }
   ]
  },
  { "title": "Fan Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "System Fan Monitor",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "System Fan 1A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 1A\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 1B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 1B\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 2A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 2A\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 2B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 2B\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 4B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 4B\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 5A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 5A\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 5B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 5B\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 6A",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 6A\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "System Fan 6B",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "VALUE",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "SENSOR:\"System Fan 6B\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  },
  {
   "title": "ETC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "BB Process VR Temp",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "BB Process1 Temperature",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "VALUE",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "SENSOR:\"BB P1 VR Temp\"",
       "timeField": "@timestamp"
      },
      {
       "alias": "BB Process2 Temperature",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "VALUE",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "SENSOR:\"BB P2 VR Temp\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Sensor Event Log",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "logs"
        }
       ],
       "query": "SELECT \"Sensor Type\" WHERE Tag:\"SEL\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}