version: '3'
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    restart: always
    build: .
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.66:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ipmi-log:1:1, sel-log:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    depends_on:
      - zookeeper

  logstash:
    restart: always
    image: logstash:7.6.1
    container_name: logstash
    command: logstash -r -f /config-dir/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    links:
      - kafka
      - elasticsearch
    volumes:
      - ./elk-conf/logstash.conf:/config-dir/logstash.conf
      - ./data/logstash/:/logstash:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
  
  # logstash-test:
  #   restart: always
  #   image: logstash:7.6.1
  #   container_name: logstash-test
  #   command: logstash -r -f /config-dir/logstash.conf
  #   ports:
  #     - "5045:5045"
  #     - "9601:9601"
  #   links:
  #     - kafka
  #     - elasticsearch
  #   volumes:
  #     - ./elk-conf/logstash-test.conf:/config-dir/logstash.conf
  #     - ./data/logstash/:/logstash:ro
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx512m -Xms512m"

  elasticsearch:
    restart: always
    image: elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
      - ./data/eslog:/var/log/elasticsearch
      - ./elk-conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  grafana:
    restart: always
    image: grafana/grafana
    container_name: grafana
    links:
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./elk-conf/grafana.ini:/usr/share/grafana/conf/defaults.ini
  
  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: tera#123
  #     MYSQL_USER: tera
  #     MYSQL_PASSWORD: xpfk#123
  #     MYSQL_DATABASE: sel
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
